name: tests-tickets

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test tickets service
        run: cd tickets && npm i && npm run test:ci
