name: tests-auth

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test auth service
        run: cd auth && npm i && npm run test:ci
